name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: v19.9.0
      - run: ls -l
      - run: cat README.md
      - run: npm install
      - run: npm run lint